### ISSUE TITLE
Missing Dependency for Google API Client (Automated error report)

### ISSUE THREAD

**Issue by themonk911** [GoogleCloudPlatform/covid-19-open-data#120]
Traceback (most recent call last):
  File "/env/lib/python3.7/site-packages/googleapiclient/discovery_cache/file_cache.py", line 33, in <module>
    from oauth2client.contrib.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client'

**Comment by owahltinez** [comment]
This appears to be an issue with the `googleapiclient` library not properly declaring the dependency on `oath2client`. We should open an issue on their project and add whatever package provides `oauth2client` to our `requirements.txt` file.

**Comment by themonk911** [comment]
It turns out this is "expected" behaviour based on how the libraries are imported. It indicates that we can't use filecaching (which should not be an issue since this is run every 12 hours). Unfortunately it means these messages are seen in the log.

https://github.com/googleapis/google-api-python-client/issues/325#issuecomment-274349841 has more details and some potential workarounds in case we do want to cach the discovery.

Closing this issue since we can safely ignore these log messages.
