### ISSUE TITLE
Oxford Government Response is now available at the US State Level

### ISSUE THREAD

**Issue by mpbrenner** [GoogleCloudPlatform/covid-19-open-data#144]
https://github.com/OxCGRT/USA-covid-policy

**Comment by mpbrenner** [comment]
Actually: The main branch has now been updated as of Aug 27th:

See below:

UPDATE: SUBNATIONAL DATA
25 August 2020 update

This coming Thursday evening UK time (27 August) we will integrate sub-national data into our two main CSVs: data/OxCGRT_latest.csv and data/OxCGRT_latest_withnotes.csv.

This may affect how you use our data. For example, for any given date, there will be 53 entries where CountryCode==USA (the existing national entry will now be accompanied by 50 states, Washington DC, and the US Virgin Islands). This may break your workflow if you assume there will be a single entry for each date with CountryCode==USA.

To distinguish between these rows in the dataset, there will be two new variables: RegionName and RegionCode. If you wish to select just for national-level data, the simplest way would be to exclude any rows where RegionCode contains any text (in other words: filter just for rows where RegionCode is null).

Once this update is complete, we will delete the temporary CSV (data/OxCGRT_US_states_temp.csv) with US state data that was uploaded on 06 August 2020.

**Comment by owahltinez** [comment]
Finally! Thanks for letting us know about this. By tonight we should have data for USA states and the nations within UK.
