### ISSUE TITLE
Add wikidata codes for districts of India

### ISSUE THREAD

**Issue by themonk911** [GoogleCloudPlatform/covid-19-open-data#146]
(many but not all) district short codes in India can be mapped to 2011 census codes via https://lgdirectory.gov.in/ which might make this easier to map to wikidata entries.

**Comment by owahltinez** [comment]
@themonk911 are you going to look into this? Otherwise I can take a stab at it this week.

**Comment by themonk911** [comment]
Hey @owahltinez , I'll take a look at it this this week - sorry it slipped!
