### ISSUE TITLE
Inconsistent site at aggregation_level = 1

### ISSUE THREAD

**Issue by alvarosg** [GoogleCloudPlatform/covid-19-open-data#152]
I was running some basic checks that all sites at aggregation_level = N, belonged to a higher order site at aggregation_level < N, in the `index` table.

I found one site: 

```
index_table[index_table["country_code"]=="Q26417"]
         key wikidata datacommons country_code country_name subregion1_code subregion1_name subregion2_code subregion2_name locality_code locality_name 3166-1-alpha-2 3166-1-alpha-3  aggregation_level
10055  LY_SR   Q26417         NaN       Q26417           LY              SR           Sirte             NaN             NaN           NaN           NaN            NaN            NaN                  1
```

with `country_code=Q26417` and `country_name=LY` which I suspect should instead be `country_code=LY` and `country_name=Libya`

**Comment by owahltinez** [comment]
Thanks for reporting! It looks like a wrong field in the metadata.csv file

**Comment by owahltinez** [comment]
This will be fixed in the next data run (within the next few hours). Don't hesitate to open more issues like this!
