### ISSUE TITLE
UK level 1 region missing deaths

### ISSUE THREAD

**Issue by jzamalloa1** [GoogleCloudPlatform/covid-19-open-data#171]
Hi,

I know that recently there was an update to include additional UK level 1 regions. I can see the cases on each of the additional regions but new deceased appear as nans, can you look into it please?

For context:
Have deceased:  ['GB_ENG' 'GB_NIR' 'GB_SCT' 'GB_WLS']
Don't have deceased: All rest GB_*

Thank you

**Comment by themonk911** [comment]
Thanks for reporting - this was an oversight. Will fix this over the weekend.

**Comment by jzamalloa1** [comment]
Thanks!
