### ISSUE TITLE
Wrong hospitalization data for UK

### ISSUE THREAD

**Issue by l2edzl3oy** [GoogleCloudPlatform/covid-19-open-data#232]
Repo has the following hospitalization data (and only for Scotland):

date | key | new_hospitalized | total_hospitalized | current_hospitalized | new_intensive_care | total_intensive_care | current_intensive_care | new_ventilator | total_ventilator | current_ventilator
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
...| ... | ... | ... | ... | ... | ...| ... | ... | ... | ... | ...
1/9/2020 | GB_SCT | 264 | 111212 |   | 6 | 7699 |   |   |   |   |  
2/9/2020 | GB_SCT | 258 | 111470 |   | 5 | 7704 |   |   |   |   |  
3/9/2020 | GB_SCT | 259 | 111729 |   | 4 | 7708 |   |   |   |   |  
4/9/2020 | GB_SCT | 258 | 111987 |   | 4 | 7712 |   |   |   |   |  
5/9/2020 | GB_SCT | 251 | 112238 |   | 4 | 7716 |   |   |   |   |  
6/9/2020 | GB_SCT | 244 | 112482 |   | 4 | 7720 |   |   |   |   |  
7/9/2020 | GB_SCT | 256 | 112738 |   | 5 | 7725 |   |   |   |   |  
8/9/2020 | GB_SCT | 267 | 113005 |   | 6 | 7731 |   |   |   |   |  
9/9/2020 | GB_SCT | 274 | 113279 |   | 6 | 7737 |   |   |   |   |  
10/9/2020 | GB_SCT | 266 | 113545 |   | 7 | 7744 |   |   |   |   |  
11/9/2020 | GB_SCT | 269 | 113814 |   | 8 | 7752 |   |   |   |   |  
12/9/2020 | GB_SCT | 261 | 114075 |   | 8 | 7760 |   |   |   |   |  
13/9/2020 | GB_SCT | 259 | 114334 |   | 7 | 7767 |   |   |   |   |  
14/9/2020 | GB_SCT | 264 | 114598 |   | 7 | 7774 |   |   |   |   |  

It does not align with the official UK data ([link](https://coronavirus.data.gov.uk/healthcare)), e.g.:
![image](https://user-images.githubusercontent.com/2408103/95727915-6b0fb880-0cad-11eb-8a7d-230f9a56a837.png)

There is ventilator data from that website as well - wondering if it could be captured.

I'd be happy to contribute (i.e. code) if that works. Thanks!

**Comment by owahltinez** [comment]
Does your recently merged PR fix this issue, or should we keep this open?

**Comment by l2edzl3oy** [comment]
> Does your recently merged PR fix this issue, or should we keep this open?

My PR was for UK country-level data (`GB` key) only. It subsumes Scotland (`GB_SCT` key), but I didn't overwrite any existing Scotland data pipeline code or output data.

The [source](https://coronavirus.data.gov.uk/) I used (from UK govt) has different Scotland numbers vs the existing Scotland numbers in this repo however. The discrepancy has not been resolved, so I think this issue should still remain open.

Any suggestions on what should be done? I'd be happy to update the existing Scotland code to use UK govt data if it makes sense.

**Comment by themonk911** [comment]
I think it makes sense to use the official source, you could also add the other nations at the same time.

**Comment by owahltinez** [comment]
Sounds good. We still need to use the existing data source for admin level 2, right? Or does the API provide that data as well?

**Comment by l2edzl3oy** [comment]
So sry for the delayed reply! Had to attend to other work.

Thanks for the confirmations - I have added the other nations (England, Northern Ireland, and Wales), and replaced the existing Scotland data source to use the [UK government data source](https://coronavirus.data.gov.uk/healthcare). See #283 .

@owahltinez Nope no need to use the existing data source for L2 data. The API provides both L1 and L2 data!

**Comment by l2edzl3oy** [comment]
Believe this issue can now be closed since PR #283 has been merged and closed :)
