### ISSUE TITLE
Invalid epidemiology data

### ISSUE THREAD

**Issue by winwiz1** [GoogleCloudPlatform/covid-19-open-data#236]
The following `epidemiology.csv` rows lack date and are invalid:
```
,SD_DC,0,,,,6,,,
,SD_DE,0,,,,21,,,
,SD_DN,0,,,,146,,,
,SD_DS,0,,,,39,,,
,SD_DW,0,,,,34,,,
,SD_GD,0,,,,274,,,
,SD_GK,0,,,,69,,,
,SD_GZ,-3,,,,1134,,,
,SD_KA,-1,,,,226,,,
,SD_KH,-45,,,,9791,,,
,SD_KN,-1,,,,202,,,
,SD_KS,-1,,,,14,,,
,SD_NB,0,,,,30,,,
,SD_NO,-1,,,,384,,,
,SD_NR,0,,,,438,,,
,SD_NW,-1,,,,190,,,
,SD_RS,-24,,,,367,,,
,SD_SI,-2,,,,241,,,
```
The rows have been identified as invalid by [Crisp CSV](https://github.com/winwiz1/crisp-csv) data validation utility (issue #186).

**Comment by owahltinez** [comment]
Thanks for reporting this, it seems like an invalid date format issue. We'll look into it.

**Comment by winwiz1** [comment]
The issue has been fixed, currently there are no CSV rows with invalid date. Closing.
