### ISSUE TITLE
Brazil COVID-19 data not loaded since 9/28/2020

### ISSUE THREAD

**Issue by emancode** [GoogleCloudPlatform/covid-19-open-data#239]
COVID-19 data for Brazil (new_confirmed, new_deceased, cumulative_confirmed, cumulative_deceased, etc.) is not available since 9/28/2020.  Data is not showing in the main.csv and epidemiology.csv files nor via BiqQuery.

Thank you for all the great work on this fantastic resource.

**Comment by owahltinez** [comment]
Thanks for the kind words and for flagging this issue. We're currently looking into it.
