### ISSUE TITLE
No recent (<98 days) data for Hong Kong

### ISSUE THREAD

**Issue by mborsetti** [GoogleCloudPlatform/covid-19-open-data#242]
(1) Hong Kong seems to be defined twice: as a country and as a China sub region.

(2) Neither has fresh data:

```
SELECT
  date, new_confirmed, new_deceased, cumulative_confirmed, cumulative_deceased
FROM
  `bigquery-public-data.covid19_open_data.covid19_open_data` 
WHERE
  country_code = "HK"
ORDER BY
  date DESC
LIMIT 100
```

returns only _null_, while

```
SELECT
  date, new_confirmed, new_deceased, cumulative_confirmed, cumulative_deceased
FROM
  `bigquery-public-data.covid19_open_data.covid19_open_data` 
WHERE
  location_key = "CN_HK"
ORDER BY
  date DESC
LIMIT 100
```

returns _null_ for any date > 2020-07-13

**Comment by owahltinez** [comment]
Thanks for reporting this, let me take a look and see what could be the issue.

**Comment by owahltinez** [comment]
We have removed the duplicate entries for `HK` and `TW` and fixed the data source. The data should now be up to date!

**Comment by mborsetti** [comment]
Thanks for the quick fix!
