### ISSUE TITLE
Date formats incorrect for LY and CZ

### ISSUE THREAD

**Issue by themonk911** [GoogleCloudPlatform/covid-19-open-data#25]
The output of epidemiology.csv has invalid date formats at the start of the file (500+ lines).

e.g.

`01.04.2020,CZ_10,,3,,,,3,,`

`07/21/2020,LY_BA,,,,,46,3,37,`

**Comment by owahltinez** [comment]
I created #26 to deal with this centrally, PTAL

**Comment by themonk911** [comment]
Looks like this is fixed, closing.
