### ISSUE TITLE
Repeated failure to download Brazil Stratified Data

### ISSUE THREAD

**Issue by themonk911** [GoogleCloudPlatform/covid-19-open-data#280]
```
{"logname": "BrazilStratifiedDataSource", "timestamp": "2020-10-29T10:00:56.5277", "classname": "BrazilStratifiedDataSource", "message": "Failed to download URL https://s3-sa-east-1.amazonaws.com/ckan.saude.gov.br/dados-mt-1.csv"}"
```

**Comment by owahltinez** [comment]
This is logged as a warning. We have to try URLs until it fails (using suffixes `-1`, `-2`, etc.). Is there a way to avoid opening bugs for warnings? When it's something worth investigating, we log an error instead.

**Comment by themonk911** [comment]
Ah I see. Closing now, currently all the logstreams are getting mashed together so it's hard to tell warnings apart from errors.
