### ISSUE TITLE
Inconsistency between json and csv by age (at least for FR)

### ISSUE THREAD

**Issue by dpshelio** [GoogleCloudPlatform/covid-19-open-data#287]
Running the following shows a discrenpancy between the JSON and the CSV by-age files:
```python
data_link = 'https://storage.googleapis.com/covid19-open-data/v2/by-age'
data_key = 'FR'
# CSV
df_age = pd.read_csv(f"{data_link}.csv").set_index("date")
print(f"Found {len(df_age.loc[df_age['key'] == data_key])} entries by age for {data_key} using csv")
#JSON
json_age = json.loads(requests.get(f"{data_link}.json").text)
key_position = json_age["columns"].index("key")
key_values = list(filter(lambda x: x[key_position] == data_key, json_age["data"]))
print(f"Found {len(key_values)} entries by age for {data_key} using json")
```
which returns
```
Found 0 entries by age for FR using csv
Found 1 entries by age for FR using json
```
Such entry refers to '2020-07-16', and that date is covered by the csv file. Looking into the history of the repository I've found that the `FR` code were updated in July (e72c1a9b67bd678430e1873394da9f58f391978b) removing the bits that were gathering FR by age and sex data (though the links removed seems to still have up-to-date data).

So, I wonder if the json files are being updated or there is something failing in the process as I'd expect both having or not the age information.

Also, note that the JSON file contains fewer entriess (1061) than the CSV (880507).

Found with @ageorgou.

**Comment by owahltinez** [comment]
Thanks for reporting this issue, I think we had some stale data in the JSON outputs. It should be fixed now, please reopen if you can still see it.
