### ISSUE TITLE
latest\main.csv not updated

### ISSUE THREAD

**Issue by Chiwidude** [GoogleCloudPlatform/covid-19-open-data#305]
The download of this link https://storage.googleapis.com/covid19-open-data/v2/latest/main.csv
does not gives the latest information, last date is September.

**Comment by Chiwidude** [comment]
Also, this file has a different column layout than the https://storage.googleapis.com/covid19-open-data/v2/main.csv file

**Comment by owahltinez** [comment]
Please see the new v3 schema: https://storage.googleapis.com/covid19-open-data/v3/latest/aggregated.csv
