### ISSUE TITLE
Sudan Data Source failing

### ISSUE THREAD

**Issue by themonk911** [GoogleCloudPlatform/covid-19-open-data#315]
{"logname": "epidemiology", "timestamp": "2020-11-18T11:09:44.5456", "classname": "DataPipeline", "loglevel": "error", "source_name": "SudanHumdataDataSource", "source_config": {"name": "pipelines.epidemiology.sd_humdata.SudanHumdataDataSource", "fetch": [{"url": "https://docs.google.com/spreadsheets/d/e/2PACX-1vQgIjG5wYFaK-z25ciiNNSWUTdxMWKRe5_y1YLNMpCzJziFor16xyP3R1nKz1wAkN7F4w6gx4F6yUIp/pub?gid=1817954914&single=true&output=csv", "opts": {"ext": "csv"}}], "test": {"location_key_match": "SD_.*"}, "automation": {"job_group": "all", "deferred": true}}, "message": "No output while saving intermediate results"}"

**Comment by owahltinez** [comment]
This is now fixed
