### ISSUE TITLE
Libya Data source failing

### ISSUE THREAD

**Issue by themonk911** [GoogleCloudPlatform/covid-19-open-data#316]
"{"logname": "epidemiology", "timestamp": "2020-11-18T11:09:41.9097", "classname": "DataPipeline", "loglevel": "error", "source_name": "LibyaHumdataDataSource", "source_config": {"name": "pipelines.epidemiology.ly_humdata.LibyaHumdataDataSource", "fetch": [{"url": "https://docs.google.com/spreadsheets/d/e/2PACX-1vQQWJZmGZJfUm22CPWoeW6rSS7Xh4K54r4A8RlN214ZCIPBUBOug3UbxFPrbiT3FQic6HS8wGdUhv3f/pub?single=true&output=csv", "opts": {"ext": "csv"}}], "test": {"location_key_match": "LY*"}, "automation": {"job_group": "all", "deferred": true}}, "message": "No output while saving intermediate results"}"

**Comment by owahltinez** [comment]
This is now working again (but still with lots of mismatches)
