### ISSUE TITLE
Poland regional data has (big) negative new cases/fatalities numbers

### ISSUE THREAD

**Issue by Datagraver** [GoogleCloudPlatform/covid-19-open-data#339]
Regional data of Poland after 24th of November suddenly has strange big negative numbers. For all regions.
![image](https://user-images.githubusercontent.com/67703609/100805450-f811fb00-342e-11eb-8d1f-98043c5d7738.png)

**Comment by themonk911** [comment]
Thanks for the bug report!

@owahltinez it looks to me that this is a case of new_confirmed being mislabelled as total_confirmed. e.g. https://open-covid-19.github.io/explorer/report/?key=PL_30 suggests that Total Confirmed cases in Greater Poland are actually only 157.

**Comment by owahltinez** [comment]
It doesn't look like we're confusing total vs new, the epi curve looks reasonable to me:
![7F8vwCZfDYT9dgN](https://user-images.githubusercontent.com/41451293/111808142-1995d600-88aa-11eb-80fd-d793c3b23dcf.png)

I think our data source here is just not very reliable. If someone can help us identify an authoritative data source for regional data in Poland we'd happily switch to that.

**Comment by owahltinez** [comment]
Fixed via #527
