### ISSUE TITLE
Invalid index data

### ISSUE THREAD

**Issue by winwiz1** [GoogleCloudPlatform/covid-19-open-data#371]
The index `DE_BE_11001` has data that appears to be invalid:
```
subregion1_code = BE
subregion1_name = 11001

subregion2_code = Berlin Mitte
subregion2_name = null
```

The [Crisp CSV](https://github.com/winwiz1/crisp-csv) utility flags other similar indices as invalid:
```
DE_BE_11002
DE_BE_11003
DE_BE_11004
DE_BE_11005
DE_BE_11006
DE_BE_11007
DE_BE_11008
DE_BE_11009
DE_BE_11010
DE_BE_11011
DE_BE_11012
```

**Comment by winwiz1** [comment]
Thank you for starting doing index validation [checks]( https://github.com/GoogleCloudPlatform/covid-19-open-data/pull/372/commits/48638ea339436f19166a102c4f32e3946d47668e#diff-aa926d05e92b4fcd1f86d9a50cff9889dc335af41885e91aceaf1b77f8c5de34) introduced today in issue: #372, commit: 48638ea339, file: src/test/test_data.py.

You are welcome to use additional constraints/data integrity rules from [Crisp CSV](https://github.com/winwiz1/crisp-csv). And to run this or similar utility, as suggested in #186, on the final production data before copying it to the production bucket. This could be considered to be a part of integration tests which compliment the unit tests introduced today. It would be consistent with common practice of maintaining data validation and integrity rules applied to any significant amount of data meant to be used by consumers.

**Comment by owahltinez** [comment]
Thanks for flagging this issue, it should now be resolved.

Even though we are open to adding post-processing validation of data, we currently do not have a lot of resources but we'll evaluate your suggestion. So far, we have only added pre-processing validation of data in the form of unit tests.
