### ISSUE TITLE
Vaccination data

### ISSUE THREAD

**Issue by tloureiro** [GoogleCloudPlatform/covid-19-open-data#378]
Are there any plans to aggregate vaccination data to this dataset?

Thanks!

**Comment by owahltinez** [comment]
Great question. We would definitely consider it if we can find reliable data sources, but for now I'm not aware of any.

**Comment by l2edzl3oy** [comment]
Vaccination data is currently available in the [Our World in Data repo](https://github.com/owid/covid-19-data/tree/master/public/data) if needed!

**Comment by tloureiro** [comment]
the sources they are using so far: https://ourworldindata.org/covid-vaccinations#source-information-country-by-country

**Comment by owahltinez** [comment]
We now have some [preliminary vaccinations data](https://github.com/GoogleCloudPlatform/covid-19-open-data/blob/main/docs/table-vaccinations.md) (mainly from OWID) but we are actively working on adding more data sources.
