### ISSUE TITLE
Invalid date for 'TH' epidemiology data

### ISSUE THREAD

**Issue by l2edzl3oy** [GoogleCloudPlatform/covid-19-open-data#379]
Epidemiology dataset (as of the time of this post) contains `2564-01-01` to `2564-01-06` for the date for the `TH` key.

**Comment by winwiz1** [comment]
Invalid dates are still in the production dataset. Can be filtered out using [Crisp CSV](https://github.com/winwiz1/crisp-csv) utility.

**Comment by owahltinez** [comment]
Fixed via #387
