### ISSUE TITLE
question about a more precise definition of mobility

### ISSUE THREAD

**Issue by khzhang** [GoogleCloudPlatform/covid-19-open-data#391]
Hi,
Thank you very much for maintaining this repository! Just a quick question about mobility. May I know a more precise definition of mobility? Is it a relative difference from the baseline? The difference from the baseline? Or something else?
Thank you very much!

**Comment by themonk911** [comment]
Hi @khzhang, this repository sources the mobility data from Google Community Mobility Reports data (https://www.google.com/covid19/mobility/). You can find out more about the data source at that link.

**Comment by khzhang** [comment]
> Hi @khzhang, this repository sources the mobility data from Google Community Mobility Reports data (https://www.google.com/covid19/mobility/). You can find out more about the data source at that link.

@themonk911 Thank you very much for your quick reply! I looked at the pages you provided, but according to it: the data for mobility describes changes for each day are compared to a baseline value for that day of the week. I guess my question is how you define the word "compare." Do you mean: the actual mobility of that day -  baseline, (the actual mobility of that day -  baseline)/baseline, or something else? Thank you very much!

**Comment by owahltinez** [comment]
Hi @khzhang, the value is a percentage. I.e. `(day - baseline) / baseline`.

**Comment by khzhang** [comment]
> Hi @khzhang, the value is a percentage. I.e. `(day - baseline) / baseline`.
That's very helpful! Thank you very much!
