### ISSUE TITLE
Provide example on how to access a specific dataset on a given date

### ISSUE THREAD

**Issue by jackap** [GoogleCloudPlatform/covid-19-open-data#392]
I want to get the main table for Italy for a specific date:
I tried
`https://storage.googleapis.com/covid19-open-data/v2/Italy-2021-02-02/main.json`
`https://storage.googleapis.com/covid19-open-data/v2/Italy-2021-02-02/main.csv`
`https://storage.googleapis.com/covid19-open-data/v2/ITA-2021-02-02/main.csv`
`https://storage.googleapis.com/covid19-open-data/v2/IT-2021-02-02/main.csv`
None of them worked. 

Perhaps adding a working example in the documentation could help understanding the indexing.
Thanks!

**Comment by owahltinez** [comment]
Hi @jackap, are you looking for a way to download data only for a specific date or for the full dataset the way it was uploaded on that date?

**Comment by jackap** [comment]
Just for a specific date, not the full dataset. Thanks

**Comment by owahltinez** [comment]
Unfortunately that's not currently possible. You'll have to download the full dataset, and then filter by the specific date. One efficient way to do this is using `curl` + `grep`.
