### ISSUE TITLE
documentation error: URL for imperial college incorrectly points to NYT

### ISSUE THREAD

**Issue by murphyk** [GoogleCloudPlatform/covid-19-open-data#407]
https://github.com/GoogleCloudPlatform/covid-19-open-data/blob/main/docs/table-epidemiology.md#sources-of-data

Also, it is not clear how data from Covid Tracking, NYT and Imperial is combined. (What is the order/ priority of each source?)

**Comment by owahltinez** [comment]
Fixed the documentation link issue.

The priority of data sources is described as part of the [configuration file](https://github.com/GoogleCloudPlatform/covid-19-open-data/blob/main/src/pipelines/epidemiology/config.yaml). Later sources override the previous ones, so in this case the priority is COVID Tracking > CDC > NYT. Imperial's data source is only being used in the `by-age` table.
