### ISSUE TITLE
documentation error: column names in .md files refer to  old (v2) schema

### ISSUE THREAD

**Issue by murphyk** [GoogleCloudPlatform/covid-19-open-data#413]
eg in
https://github.com/GoogleCloudPlatform/covid-19-open-data/blob/main/docs/table-epidemiology.md
we should replace 'total_confirmed' with 'cumulative_confirmed'

**Comment by owahltinez** [comment]
Right, this is pending the official "launch" of the v3 schema. It's not really a secret, but we want to do it in coordination with the data being updated in BQ just in case we need to make any adjustments to field names.

**Comment by owahltinez** [comment]
@a27cheung is currently working on this

**Comment by a27cheung** [comment]
Hi @murphyk - will get to it as soon as we’re done with the large presentation we have for this week! Apologies for the lag :(

**Comment by owahltinez** [comment]
Fixed via #490
