### ISSUE TITLE
aggregated table is missing one of the google search terms (columns)

### ISSUE THREAD

**Issue by murphyk** [GoogleCloudPlatform/covid-19-open-data#415]
missing 'search_trends_generalized_tonic–clonic_seizure'
There are 422 columns in the google table, but only 421 in the aggregated table.

**Comment by owahltinez** [comment]
Thanks for reporting this! It should be fixed via https://github.com/GoogleCloudPlatform/covid-19-open-data/commit/36a125cc2d0e4220c3e5158b302d653157dc9ea2 (we remove all dashes, but that symptom name has a special character dash which we didn't account for)
