### ISSUE TITLE
documentation error: google search trends incorrectly lists geo information

### ISSUE THREAD

**Issue by murphyk** [GoogleCloudPlatform/covid-19-open-data#416]
https://github.com/GoogleCloudPlatform/covid-19-open-data/blob/main/docs/table-search-trends.md
The following columsn are not actually stored

country_region 
country_region_code 
sub_region_1
sub_region_1_code 
sub_region_2 
sub_region_2_code

**Comment by owahltinez** [comment]
Good catch! Thanks for reporting this. We forgot to update the docs after we started processing the data (since those fields are available in the original data source)
