### ISSUE TITLE
Missing EMS data for Epidemiology in France (FR)

### ISSUE THREAD

**Issue by dugwood** [GoogleCloudPlatform/covid-19-open-data#426]
Hello,

Number of deaths in France is wrong, as France doesn't include deaths in specialized care units (for elder people), hence we can see this difference (for March 3rd 2021):

epidemiology.csv:
> 2021-03-03,FR,26788,322,261289,,3810125,**62569**,39964358,53548191

But on the French website: https://www.santepubliquefrance.fr/dossiers/coronavirus-covid-19/coronavirus-chiffres-cles-et-evolution-de-la-covid-19-en-france-et-dans-le-monde

![image](https://user-images.githubusercontent.com/5517743/109931183-d1cb5800-7cc8-11eb-98d3-2fdf913866a5.png)

> 87568 deaths, of which 62595 in the hospital

(Which is close to the 62569 number above, some data is changing along the way)

Data is available here: https://www.data.gouv.fr/fr/datasets/synthese-des-indicateurs-de-suivi-de-lepidemie-covid-19/ (second dataset)
> 'esms_dc'= Décès en EHPAD et ESMS

Perhaps adding this as a fake region would be a good idea (such as FR_IDF stands for «Île de France», it could be «FR_ESMS»).

Thanks for this project!

**Comment by owahltinez** [comment]
Thanks for reporting this and for the kind words @dugwood!

> Data is available here: https://www.data.gouv.fr/fr/datasets/synthese-des-indicateurs-de-suivi-de-lepidemie-covid-19/ (second dataset)

We will update our data source to this which seems more accurate, thanks for the pointer.

> Perhaps adding this as a fake region would be a good idea (such as FR_IDF stands for «Île de France», it could be «FR_ESMS»).

I like this idea, it's one of the reasons why we have a "special aggregation level" — so we can report data for non-standard "localities". Let me chat about this with the team, although it's definitely a lower priority than reporting the appropriate country-wide numbers.

**Comment by owahltinez** [comment]
We've now fixed the undercounting and France includes deaths from ESMS. I'm not happy about how subregions do not have this data, but I don't think there's anything we can do about it...

We have not added an ESMS region yet — we'll consider that for future work. But I'm closing this issue for now since the main problem has been resolved.
