### ISSUE TITLE
Vaccinations Table is not present on main list of tables on the homepage

### ISSUE THREAD

**Issue by mpbrenner** [GoogleCloudPlatform/covid-19-open-data#428]

**Comment by owahltinez** [comment]
@a27cheung is currently working on this

**Comment by a27cheung** [comment]
Hi @mpbrenner - apologies for the lag! We’re working on a presentation to a large audience this week. I’ll get to this as soon as possible :)

**Comment by Abhishek0786** [comment]
@owahltinez 
any update??

**Comment by owahltinez** [comment]
Fixed via #490
