### ISSUE TITLE
Moscow Russia data is incorrect

### ISSUE THREAD

**Issue by Pyc01** [GoogleCloudPlatform/covid-19-open-data#433]
Hi, at least the following data is incorrect for Moscow, Russia:
'total_confirmed' 
'new_confirmed'
'new_deceased'
in https://storage.googleapis.com/covid19-open-data/v2/latest/main.csv

Occasionally (approximately one day a week) the data becomes resonable, but next day it shows very low values.

Also, the 'date' column is questionable. It shows day ahead currently.

Kind regards.

**Comment by owahltinez** [comment]
Hi @Pyc01, thanks for reporting this issue.

What would be the correct data? Currently, our data source for regional data in Russia is [this portal](https://xn--80aesfpebagmfblc0a.xn--p1ai/).

**Comment by owahltinez** [comment]
I think this issue could be related to what #435 fixes, please confirm if you are still seeing the issues you described.

**Comment by Pyc01** [comment]
Hi, @owahltinez, sorry for the delay in reply back.
Yes, the source is good but the data extracted was incorrect. There are more than a million cases in Moscow, but two days ago it showed 99 cases only.
Today the data seems to be correct: 1,008,224 cases in total which matches the portal data.
Many thanks for your help and kind regards!
