### ISSUE TITLE
Example data download notebook not working--error received when loading

### ISSUE THREAD

**Issue by Rmonty1** [GoogleCloudPlatform/covid-19-open-data#472]

**Comment by Rmonty1** [comment]
Tried to open/download the example Jupyter nb.  Errors out on load.  Get file corupt error after downloading and trying to open in Anconda.

**Comment by owahltinez** [comment]
Can you please provide the exact URL which is causing issues?

**Comment by kl692** [comment]
Same issue. Received the following error:

Error loading notebook
Unreadable Notebook: PATH\covid-19-open-data-main\examples\data_loading.ipynb NotJSONError('Notebook does not appear to be JSON: \'{\\n "cells": [\\n {\\n "cell_type": "m...')

**Comment by owahltinez** [comment]
Thanks for reporting this, it should be fixed now via #490
