### ISSUE TITLE
Vaccinations .csv or .json data is not coming based on the date

### ISSUE THREAD

**Issue by Abhishek0786** [GoogleCloudPlatform/covid-19-open-data#477]
Date format given on website:  (YYYY-MM-DD)

This is the URL I am using to fetch the vaccinations data: **https://storage.googleapis.com/covid19-open-data/v2/2021-02-07/vaccinations.json**

Could you help  is there something wrong above the url?. I have attached the error image for your reference.

![image](https://user-images.githubusercontent.com/21989287/121319473-dfc4f080-c929-11eb-8fb1-96ed8ffb65f5.png)

**Comment by owahltinez** [comment]
The name of the file is: https://storage.googleapis.com/covid19-open-data/v2/vaccinations.json

**Comment by Abhishek0786** [comment]
Hi @owahltinez 
I want to get the vaccination based on key defined in vaccinations.json file. 
E.G: I want to get the data of vaccination of "BR" key in the vaccinations.json file.

**Comment by dugwood** [comment]
> Hi @owahltinez
> I want to get the vaccination based on key defined in vaccinations.json file.
> E.G: I want to get the data of vaccination of "BR" key in the vaccinations.json file.

You should just read the main page: https://github.com/GoogleCloudPlatform/covid-19-open-data#use-the-data

> Data for key in CSV format: https://storage.googleapis.com/covid19-open-data/v3/location/${key}.csv
> Data for key in JSON format: https://storage.googleapis.com/covid19-open-data/v3/location/${key}.json
