### ISSUE TITLE
How to get the vaccination data country wise.

### ISSUE THREAD

**Issue by Abhishek0786** [GoogleCloudPlatform/covid-19-open-data#479]
**Vaccinations data:** https://storage.googleapis.com/covid19-open-data/v2/vaccinations.json

I want to get the vaccination data country wise not all countries. how I can achieve this?. I have tried with "key" but it is not working.
@owahltinez

**Comment by owahltinez** [comment]
Please try `https://storage.googleapis.com/covid19-open-data/v3/location/${location_key}.json`. For example, Thailand: https://storage.googleapis.com/covid19-open-data/v3/location/TH.json

**Comment by surijatin** [comment]
@owahltinez I went through the response for this API, the vaccination data doesn't look like it being maintained anymore. Checked for the Thailand and India.

**Comment by owahltinez** [comment]
Vaccination data is being maintained, but it does not update at the same rate for all locations. It's highly dependent on data availability from the local health authorities.
