### ISSUE TITLE
Mobility data for GB_ENG_LON

### ISSUE THREAD

**Issue by jojo453** [GoogleCloudPlatform/covid-19-open-data#482]
Mobility data for GB_ENG_LON is showing as several hundred or thousand, which should not be possible.

**Comment by owahltinez** [comment]
Thanks for reporting this. It appears to be an issue with how we aggregate data from the different locations that represent `GB_ENG_LON`. It should be fixed shortly.

**Comment by jojo453** [comment]
@owahltinez Thanks very much for correcting this.
