### ISSUE TITLE
Data extraction question

### ISSUE THREAD

**Issue by sargent1234** [GoogleCloudPlatform/covid-19-open-data#501]
Hello -- I am hoping to extract the following data: 

Daily vaccination rates (at least one dose) by US state among the adult population (18+ years old). 

I see that this information is not readily available in one of the data files. I also see that the age brackets go from 0-18 and 19+. Is it possible to obtain these data from these files? 

Thank you for your time and guidance.

**Comment by owahltinez** [comment]
Hello @sargent1234. Unfortunately we do not provide stratified vaccination data at the moment.
