### ISSUE TITLE
Cannot load the full aggregated data

### ISSUE THREAD

**Issue by jhammarstedt** [GoogleCloudPlatform/covid-19-open-data#516]
Hi, 
In the data_loading notebook you showcase the simple example of how to get the last day of data and then refer to the same link for downloading all data?

The one I load is also only 22k records ? What is the URL to get the full dataset?
Thanks!

**Comment by owahltinez** [comment]
Please see the documentation at https://goo.gle/covid-19-open-data. The file you are looking for is probably [this one](https://storage.googleapis.com/covid19-open-data/v3/aggregated.csv.gz).
