### ISSUE TITLE
Brazil epi total_recovered contains wrong data

### ISSUE THREAD

**Issue by nicfreeman1209** [GoogleCloudPlatform/covid-19-open-data#53]
For BR, on 20/04/2020 and later dates, total_recovered is significantly greater than total_cases. It looks as though total_recovered is the running sum of new_recovered, so both contain wrong data.

Perhaps: what is currently in BR new_recovered should go in BR total_recovered?

**Comment by owahltinez** [comment]
Thanks for reporting! It looks like the data sources incorrectly labeled the cumulative cases as "new" like you suggested.
