### ISSUE TITLE
India regions stopped 31 Oct 2021

### ISSUE THREAD

**Issue by Datagraver** [GoogleCloudPlatform/covid-19-open-data#533]
Dear all,
The data for the regions in India stopped at 31 Oct 2021. Might be because of change in source data? Would appreciate it being added again for our world charts:
https://covid19.innouveau.com/#/?map=South-East%20Asia&language=en

Best regards
Stephan Okhuijsen
Aka Datagraver

**Comment by themonk911** [comment]
Hi DataGraver,

Our data source (covid19india.org) has unfortunately stopped producing statewide/district data post Oct 31. We're looking for a suitable replacement at the moment.

Thanks,
Mayank

**Comment by themonk911** [comment]
This issue should now be resolved.
