### ISSUE TITLE
weather data in not updating past 2021

### ISSUE THREAD

**Issue by mrahman-8** [GoogleCloudPlatform/covid-19-open-data#539]

**Comment by Manu-035** [comment]
Too bad if weather in not supported in 2022, as this dataset is used to follow the link between temperature and viral reproduction ratio (R). See e.g. https://twitter.com/flight_behav/status/1460717831612518407?s=20 and https://www.medrxiv.org/content/10.1101/2021.01.29.21250793v1
Plese keep on this fantastic work !

**Comment by owahltinez** [comment]
Thanks for reporting! Fixed via #541
