### ISSUE TITLE
No Vaccine counts for US counties since 19Feb2022 in https://storage.googleapis.com/covid19-open-data/v3/vaccinations.csv

### ISSUE THREAD

**Issue by johncdavis200** [GoogleCloudPlatform/covid-19-open-data#543]
I download this vaccine data file daily and since 20Feb2022 the counts for all US counties/states/etc have been zero.  Can someone please check this data and fix the problem or at least document why it has stopped and when it will return.  Thanks!

**Comment by owahltinez** [comment]
Hello @johncdavis200, thanks for reporting this! The data is collected from the CDC, and it seems that the CDC has not updated it since Feb 19: https://covid.cdc.gov/covid-data-tracker/COVIDData/getAjaxData?id=vaccination_county_condensed_data

**Comment by johncdavis200** [comment]
Thanks for the quick response... hopefully they will correct that soon.

**Comment by owahltinez** [comment]
It appears to be fixed now
