### ISSUE TITLE
Missing new and cumulative cases for Czechia

### ISSUE THREAD

**Issue by MagnusBook** [GoogleCloudPlatform/covid-19-open-data#547]
I'm using this data for some research, and noticed a big chunk of missing data for Czechia. It seems like both the new confirmed and cumulative cases remain at 0 until 2021-08-12, where it suddenly spikes to the correct values. See the table below for an illustration of the problem.

| date       | location_key | new_confirmed | new_deceased | new_recovered | new_tested | cumulative_confirmed | cumulative_deceased | cumulative_recovered | cumulative_tested |
|------------|--------------|---------------|--------------|---------------|------------|----------------------|---------------------|----------------------|-------------------|
| 2021-08-09 | CZ           | 0             | 1            | 254           | 33911      | 0                    | 30488               | 1638970              | 9336548           |
| 2021-08-10 | CZ           | 0             | 0            | 188           | 34650      | 0                    | 30488               | 1639158              | 9371198           |
| 2021-08-11 | CZ           | 0             | 1            | 204           | 112354     | 0                    | 30489               | 1639362              | 34850816          |
| 2021-08-12 | CZ           | 188           | 0            | 170           | 168410     | 1662121              | 30489               | 1639532              | 35019226          |
| 2021-08-13 | CZ           | 216           | 0            | 131           | 100069     | 1662337              | 30489               | 1639663              | 35119295          |
| 2021-08-14 | CZ           | 141           | 0            | 89            | 67948      | 1662478              | 30489               | 1639752              | 35187243          |

As far as I can tell, the new and cumulative cases columns are the only ones that have this problem.

**Comment by owahltinez** [comment]
It appears to be an issue with the [data source](https://onemocneni-aktualne.mzcr.cz). It seems to be publishing constant zeroes for the [country data](https://onemocneni-aktualne.mzcr.cz/api/v2/covid-19/nakaza.csv). If it's not fixed soon, we can just remove this data source and use the numbers from the WHO.
