### ISSUE TITLE
Both epidemiology.csv files (latest and full) contain JP only.

### ISSUE THREAD

**Issue by winwiz1** [GoogleCloudPlatform/covid-19-open-data#59]
Both files `storage.googleapis.com/covid19-open-data/v2/epidemiology.csv` and `storage.googleapis.com/covid19-open-data/v2/latest/epidemiology.csv` contain a subset of data it used to have.

**Comment by owahltinez** [comment]
Thank you for reporting this. We accidentally uploaded a bad config file last night, it should be fixed now. I'll try to force a purge of the bad data within the next hour.

**Comment by owahltinez** [comment]
The bad data appears to be purged now :-)

**Comment by winwiz1** [comment]
Thank you for fixing.
