### ISSUE TITLE
Spain level 1 data

### ISSUE THREAD

**Issue by jzamalloa1** [GoogleCloudPlatform/covid-19-open-data#68]
Hi,

I see that the data for Spain at subregion1_name in cases goes only at 8/2 (main) and 8/3(epi). Could you double check the source please?

Thank you

**Comment by owahltinez** [comment]
Thanks for flagging. I just checked, and the source appears to be a little behind and has not been updated for over a week: https://cnecovid.isciii.es/covid19/

Number of deceased cases is coming from a different file within the [Ministry of Health](https://www.mscbs.gob.es/) which is still being updated.

I'll keep an eye on it; if the problems with this data source persist, we can look into processing each subregion independently. We also want to add admin level 2 data for the subregions that have that level of granularity available, but it's in the backlog for now.

**Comment by jzamalloa1** [comment]
Thank you, that would be really helpful (aggregating level 2 to level 1 if the data is not coming through).

**Comment by jzamalloa1** [comment]
Sorry to ask again, but would it be possible to aggregate from level 2 if the data is available?

**Comment by owahltinez** [comment]
We currently only have data for ES_CN at admin level 2, and we are aggregating admin level 1 from it. If you have a list of admin level 1 regions and their respective data sources, we can try to prioritize that.

**Comment by jzamalloa1** [comment]
Hi, I wanted to follow up on this. I found a source that may contain more up to date and granular data:

https://cnecovid.isciii.es/covid19/#documentación-y-datos

Would it be possible to integrate it?

Thanks

**Comment by owahltinez** [comment]
Thanks for the pointer! That's the data source we are currently using, which finally issued an update and now there's data up to August 9.

We are still looking for municipality-level data sources for each of the autonomous communities, but that work continues to be preempted by higher priority requests.

**Comment by owahltinez** [comment]
FYI we were able to find data sources for ES_CN and ES_MD but so far nothing for most other regions. The admin level 1 data source continues to update regularly, just not daily like most other data sources. I'll close this since there's not much we can do about it.

**Comment by jzamalloa1** [comment]
Thank you, I appreciate all the hard work put on this!
