### ISSUE TITLE
UK authority data source changed API/death processing

### ISSUE THREAD

**Issue by themonk911** [GoogleCloudPlatform/covid-19-open-data#95]
```
RuntimeError: Request failed: {"response":"Invalid parameter 'newDeathsByPublishDate' in the requested JSON structure. Did you mean 'newTestsByPublishDate'?","status_code":404,"status":"Not Found"}
at _get (/env/lib/python3.7/site-packages/uk_covid19/api_interface.py:226)
at get_json (/env/lib/python3.7/site-packages/uk_covid19/api_interface.py:278)
at parse (/home/vmagent/app/pipelines/epidemiology/gb_authority.py:102)
at parse (/home/vmagent/app/pipelines/epidemiology/gb_authority.py:131)
at run (/home/vmagent/app/lib/data_source.py:226)
at _run_wrapper (/home/vmagent/app/lib/pipeline.py:164)
```

The UK govt is changing the way they report deaths. From the official document (https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/908781/Technical_Summary_PHE_Data_Series_COVID-19_Deaths_20200812.pdf)

> There are 2 definitions of a death in a person with COVID-19 in England, one
> broader measure and one measure reflecting current trends:
> 1) A death in a person with a laboratory-confirmed positive COVID-19 test and
> either died within 60 days of the first specimen date or died more than 60 days
> after the first specimen date, only if COVID-19 is mentioned on the death
> certificate
> 2) A death in a person with a laboratory-confirmed positive COVID-19 test and
> died within (equal to or less than) 28 days of the first positive specimen date
> c. A measure of acute deaths which can be used to understand current trends is
> further defined as a “a death in any person with a laboratory-confirmed positive
> COVID-19 test AND within (equal to or less than) 28 days of the first positive
> specimen date.

Unfortunately they already changed the API.

**Comment by themonk911** [comment]
I propose that we use the broader definition (60 days) rather than the "acute" definition. @owahltinez what do you think?

**Comment by owahltinez** [comment]
What definition is being used to report aggregated numbers, e.g. to the WHO or the ECDC?

**Comment by themonk911** [comment]
Apparently neither - "The WHO recommendation is to report on death certification, which England will continue to do through the ONS. For daily reported death figures, there is no international consensus on methods."

**Comment by themonk911** [comment]
Unfortunately the ONS only reports weekly.

**Comment by owahltinez** [comment]
I see. I don't feel strongly about either metric, my preference is to use whichever gets us "closer" to the number of deaths reported through the ONS.

**Comment by themonk911** [comment]
It looks like the 60days version does not work through the API - in order to continue reporting I'm moving to the 28 days version. It's also what is now reported on the official website - https://coronavirus.data.gov.uk/
